### ISSUE TITLE
请问这里的dotnet是新世界还是老世界的？

### ISSUE THREAD

**Issue by driver1998** [shushanhf/LoongArch64-Blog-for-.NET-Mono#3]
现在LA的dotnet应该只有你这个repo，以及loongnix.cn有二进制包
上游的代码我猜应该是适配新世界ABI的，loongnix.cn上的包是老世界的，请问repo这里的包呢？

如果要新世界的dotnet，是要从源码编译吗？

**Comment by shushanhf** [comment]
不知道你是从哪里 得知这个 “新世界”  的叫法的；应该是关注相关专业的技术内行。

首先，基于上游社区构建的LA64的OS系统，目前应该还没有对应OS发行版出来。
如果有基于上游社区构建的OS发行版，我们会发布对应OS环境系统的dotnet-SDK版本。

**Comment by driver1998** [comment]
基于上游社区构建的OS发行版，感觉现在已经逐渐成熟了。最近龙芯官方也宣传了LA的Arch Linux。
可以考虑给Arch打一个包？

**Comment by shushanhf** [comment]
> 基于上游社区构建的OS发行版，感觉现在已经逐渐成熟了。最近龙芯官方也宣传了LA的Arch Linux。 可以考虑给Arch打一个包？

之前我们组为了方便验证，dotnet呢确实一直是使用所谓的旧世界来构建，（对dotnet来说切换过去就是一个小patch）这个patch我们计划在8月初完成提交（我们环境切换过渡需要多测试一下）。

我们今天会把SDK8.0-preview6上传一下。

基于最新上游社区构建SDK包，我们稍微晚点上传。
